spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swboardprototype?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true

jwt:
  key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  access-token-expiration-minutes: 1444
  refresh-token-expiration-minutes: 1444